/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppComplaintsIndexRouteImport } from './routes/_app.complaints.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppComplaintsNewRouteImport } from './routes/_app.complaints.new'
import { Route as AppComplaintsIdRouteImport } from './routes/_app.complaints.$id'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminNoticesRouteImport } from './routes/_app.admin.notices'
import { Route as AppAdminComplaintsIndexRouteImport } from './routes/_app.admin.complaints.index'
import { Route as AppAdminComplaintsIdRouteImport } from './routes/_app.admin.complaints.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIndexRoute = AppComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppComplaintsNewRoute = AppComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIdRoute = AppComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminNoticesRoute = AppAdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminComplaintsIndexRoute = AppAdminComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminComplaintsIdRoute = AppAdminComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/notices': typeof AppNoticesRoute
  '/profile': typeof AppProfileRoute
  '/admin/notices': typeof AppAdminNoticesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/complaints/': typeof AppComplaintsIndexRoute
  '/admin/complaints/$id': typeof AppAdminComplaintsIdRoute
  '/admin/complaints/': typeof AppAdminComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/notices': typeof AppNoticesRoute
  '/profile': typeof AppProfileRoute
  '/admin/notices': typeof AppAdminNoticesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/complaints': typeof AppComplaintsIndexRoute
  '/admin/complaints/$id': typeof AppAdminComplaintsIdRoute
  '/admin/complaints': typeof AppAdminComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/admin/notices': typeof AppAdminNoticesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/complaints/$id': typeof AppComplaintsIdRoute
  '/_app/complaints/new': typeof AppComplaintsNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/complaints/': typeof AppComplaintsIndexRoute
  '/_app/admin/complaints/$id': typeof AppAdminComplaintsIdRoute
  '/_app/admin/complaints/': typeof AppAdminComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/notices'
    | '/profile'
    | '/admin/notices'
    | '/admin/settings'
    | '/complaints/$id'
    | '/complaints/new'
    | '/admin/'
    | '/complaints/'
    | '/admin/complaints/$id'
    | '/admin/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/dashboard'
    | '/notices'
    | '/profile'
    | '/admin/notices'
    | '/admin/settings'
    | '/complaints/$id'
    | '/complaints/new'
    | '/admin'
    | '/complaints'
    | '/admin/complaints/$id'
    | '/admin/complaints'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/register'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/notices'
    | '/_app/profile'
    | '/_app/admin/notices'
    | '/_app/admin/settings'
    | '/_app/complaints/$id'
    | '/_app/complaints/new'
    | '/_app/admin/'
    | '/_app/complaints/'
    | '/_app/admin/complaints/$id'
    | '/_app/admin/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/': {
      id: '/_app/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AppComplaintsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/complaints/new': {
      id: '/_app/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AppComplaintsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/$id': {
      id: '/_app/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AppComplaintsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/notices': {
      id: '/_app/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AppAdminNoticesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/complaints/': {
      id: '/_app/admin/complaints/'
      path: '/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AppAdminComplaintsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/complaints/$id': {
      id: '/_app/admin/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AppAdminComplaintsIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminNoticesRoute: typeof AppAdminNoticesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminComplaintsIdRoute: typeof AppAdminComplaintsIdRoute
  AppAdminComplaintsIndexRoute: typeof AppAdminComplaintsIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminNoticesRoute: AppAdminNoticesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminComplaintsIdRoute: AppAdminComplaintsIdRoute,
  AppAdminComplaintsIndexRoute: AppAdminComplaintsIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppComplaintsIdRoute: typeof AppComplaintsIdRoute
  AppComplaintsNewRoute: typeof AppComplaintsNewRoute
  AppComplaintsIndexRoute: typeof AppComplaintsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppProfileRoute: AppProfileRoute,
  AppComplaintsIdRoute: AppComplaintsIdRoute,
  AppComplaintsNewRoute: AppComplaintsNewRoute,
  AppComplaintsIndexRoute: AppComplaintsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
